---

- name: Fail if {{ snapshot_config.name }} is not found
  ansible.builtin.fail:
    msg: "ZFS volume {{ snapshot_config.name }} not found"
  when: snapshot_config.name not in zfs_auto_snapshot_volume_names_cmd.stdout_lines

- name: Set snapshot_config variables
  tags: zfs_auto_snapshot
  set_fact:
    _disabled: "{{ snapshot_config.disabled | default(false) }}"
    _frequent: "{{ snapshot_config.frequent | default(false) }}"
    _hourly: "{{ snapshot_config.hourly | default(false) }}"
    _daily: "{{ snapshot_config.daily | default(false) }}"
    _weekly: "{{ snapshot_config.weekly | default(false) }}"
    _monthly: "{{ snapshot_config.monthly | default(false) }}"

- name: "Check enabled {{ snapshot_config.name }}"
  tags: zfs_auto_snapshot
  shell: 
    cmd: |
      zfs get com.sun:auto-snapshot {{ snapshot_config.name }} \
      | tail -n +2 \
      | sed 's/[ \t]\+/ /g' \
      | cut -d ' ' -f 3
  register: _is_enabled_cmd
  changed_when: no
  failed_when: no

- name: "Disable snapshots {{ snapshot_config.name }}"
  tags: zfs_auto_snapshot
  shell: "zfs set com.sun:auto-snapshot=false {{ snapshot_config.name }}"
  when: _disabled and _is_enabled_cmd.stdout != 'false'

- name: "Enable snapshots {{ snapshot_config.name }}"
  tags: zfs_auto_snapshot
  shell: "zfs set com.sun:auto-snapshot=true {{ snapshot_config.name }}"
  when: (_frequent or _hourly or _daily or _weekly or _monthly) and _is_enabled_cmd.stdout != 'true' and not _disabled

- name: "Check frequent {{ snapshot_config.name }}"
  tags: zfs_auto_snapshot
  shell: "zfs get com.sun:auto-snapshot.frequent {{ snapshot_config.name }} | grep -q '[ \t ]true'"
  register: _is_frequent_true
  changed_when: no
  failed_when: no

- name: "Enable frequent {{ snapshot_config.name }}"
  tags: zfs_auto_snapshot
  shell: "zfs set com.sun:auto-snapshot.frequent={{ _frequent | lower }} {{ snapshot_config.name }}"
  when: (_is_frequent_true.rc == 0 and not _frequent) or (_is_frequent_true.rc != 0 and _frequent)

- name: "Check hourly {{ snapshot_config.name }}"
  tags: zfs_auto_snapshot
  shell: "zfs get com.sun:auto-snapshot.hourly {{ snapshot_config.name }} | grep -q '[ \t ]true'"
  register: _is_hourly_true
  changed_when: no
  failed_when: no

- name: "Enable hourly {{ snapshot_config.name }}"
  tags: zfs_auto_snapshot
  shell: "zfs set com.sun:auto-snapshot.hourly={{ _hourly | lower }} {{ snapshot_config.name }}"
  when: (_is_hourly_true.rc == 0 and not _hourly) or (_is_hourly_true.rc != 0 and _hourly)

- name: "Check daily {{ snapshot_config.name }}"
  tags: zfs_auto_snapshot
  shell: "zfs get com.sun:auto-snapshot.daily {{ snapshot_config.name }} | grep -q '[ \t ]true'"
  register: _is_daily_true
  changed_when: no
  failed_when: no

- name: "Enable daily {{ snapshot_config.name }}" 
  tags: zfs_auto_snapshot
  shell: "zfs set com.sun:auto-snapshot.daily={{ _daily | lower }} {{ snapshot_config.name }}"
  when: (_is_daily_true.rc == 0 and not _daily) or (_is_daily_true.rc != 0 and _daily)

- name: "Check weekly {{ snapshot_config.name }}"
  tags: zfs_auto_snapshot
  shell: "zfs get com.sun:auto-snapshot.weekly {{ snapshot_config.name }} | grep -q '[ \t ]true'"
  register: _is_weekly_true
  changed_when: no
  failed_when: no

- name: "Enable weekly {{ snapshot_config.name }}"
  tags: zfs_auto_snapshot
  shell: "zfs set com.sun:auto-snapshot.weekly={{ _weekly | lower }} {{ snapshot_config.name }}"
  when: (_is_weekly_true.rc == 0 and not _weekly) or (_is_weekly_true.rc != 0 and _weekly)

- name: "Check monthly {{ snapshot_config.name }}"
  tags: zfs_auto_snapshot
  shell: "zfs get com.sun:auto-snapshot.monthly {{ snapshot_config.name }} | grep -q '[ \t ]true'"
  register: _is_monthly_true
  changed_when: no
  failed_when: no

- name: "Enable monthly {{ snapshot_config.name }}"
  tags: zfs_auto_snapshot
  shell: "zfs set com.sun:auto-snapshot.monthly={{ _monthly | lower }} {{ snapshot_config.name }}"
  when: (_is_monthly_true.rc == 0 and not _monthly) or (_is_monthly_true.rc != 0 and _monthly)
