---

- name: Get volume names
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      zfs list | tail -n +2 | cut -d " " -f 1
    executable: "{{ zfs_auto_snapshot_cmd_executable }}"
  changed_when: no
  register: zfs_auto_snapshot_volume_names_cmd

- name: Get pool names
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      zpool list | tail -n +2 | cut -d " " -f 1
    executable: "{{ zfs_auto_snapshot_cmd_executable }}"
  changed_when: no
  register: zfs_auto_snapshot_pool_names_cmd

- name: Set zfs-auto-snapshot properties
  ansible.builtin.include_tasks: tasks/set_labels.yml
  loop: "{{ zfs_auto_snapshot_config | list }}"
  loop_control:
    loop_var: snapshot_config

- name: Install zfs-auto-snapshot frequent cron job
  ansible.builtin.template:
    src: zfs-auto-snapshot.frequent.j2
    dest: /etc/cron.d/zfs-auto-snapshot
    mode: '0644'
    owner: root
    group: root

- name: Install zfs-auto-snapshot cron jobs
  ansible.builtin.template:
    src: zfs-auto-snapshot.j2
    dest: /etc/cron.{{ item.label }}/zfs-auto-snapshot
    mode: '0644'
    owner: root
    group: root
  loop:
    - label: hourly
      keep: "{{ zfs_auto_snapshot_hourly_keep }}"
    - label: daily
      keep: "{{ zfs_auto_snapshot_daily_keep }}"
    - label: weekly
      keep: "{{ zfs_auto_snapshot_weekly_keep }}"
    - label: monthly
      keep: "{{ zfs_auto_snapshot_monthly_keep }}"
